###
GET http://localhost:4000/courses HTTP/1.1

###
GET http://localhost:4000/courses/633ee680556cd7776a5ea787 HTTP/1.1
###
GET http://localhost:4000/courses/633ef4293b8db1dab50b4de1/students HTTP/1.1
###
POST http://localhost:4000/courses HTTP/1.1
Content-Type: application/json

{
    "year_of_dictation": 2023,
    "duration": "2 months",
    "theme": "Bases de datos no relacionales",
    "students":[
        {
        "name": "Prueba",
        "last_name": "Prueba",
        "dni": 123456,
        "adress": "calle falsa 123"
    },
    {
        "name": "Prueba2",
        "last_name": "Prueba2",
        "dni": 1234565,
        "adress": "calle falsa 1234"
    }
    ]
}

###
DELETE http://localhost:4000/courses/633ee680556cd7776a5ea787 HTTP/1.1